/**
 * Azure Notification Hubs service wrapper.
 *
 * Exposes helpers to:
 *  - create/update a device installation (register)
 *  - update tags on an existing installation
 *  - delete an installation
 *  - send a push to a specific user tag  (user:<userId>)
 *  - send a push to a tag expression     (e.g. "role:employer && niche:Gastronomia")
 *
 * All methods return { success: false, error } when ANH is not configured so
 * callers can surface a graceful 503 without crashing.
 */

import {
  NotificationHubsClient,
  createAppleInstallation,
  createFcmV1Installation,
  createAppleNotification,
  createFcmV1Notification,
} from '@azure/notification-hubs';
import { env } from '../config/env.js';

/** Returns a NotificationHubsClient instance, or null when ANH is not configured. */
function getClient() {
  if (!env.ANH_CONNECTION_STRING || !env.ANH_HUB_NAME) return null;
  return new NotificationHubsClient(env.ANH_CONNECTION_STRING, env.ANH_HUB_NAME);
}

/**
 * Register (create or update) a device installation.
 *
 * @param {object} params
 * @param {string} params.installationId  - Stable device identifier (e.g. UUID generated by the client app)
 * @param {'apns'|'fcmv1'} params.platform
 * @param {string} params.pushToken       - Device push token / registration token
 * @param {string[]} params.tags          - e.g. ["user:abc123", "role:freelancer", "niche:Gastronomia"]
 */
export async function registerInstallation({ installationId, platform, pushToken, tags = [] }) {
  const client = getClient();
  if (!client) return { success: false, error: 'Notification Hubs not configured' };

  try {
    const base = { installationId, tags, pushChannel: pushToken };
    const installation =
      platform === 'apns'
        ? createAppleInstallation(base)
        : createFcmV1Installation(base);

    await client.createOrUpdateInstallation(installation);
    return { success: true };
  } catch (err) {
    console.error('[notificationHubs.registerInstallation]', err.message);
    return { success: false, error: err.message };
  }
}

/**
 * Update only the tags of an existing installation via JSON-Patch.
 *
 * @param {string} installationId
 * @param {string[]} tags
 */
export async function updateInstallationTags(installationId, tags = []) {
  const client = getClient();
  if (!client) return { success: false, error: 'Notification Hubs not configured' };

  try {
    const patchOps = [{ op: 'replace', path: '/tags', value: tags }];
    await client.updateInstallation(installationId, patchOps);
    return { success: true };
  } catch (err) {
    console.error('[notificationHubs.updateInstallationTags]', err.message);
    return { success: false, error: err.message };
  }
}

/**
 * Remove a device installation from Azure Notification Hubs.
 *
 * @param {string} installationId
 */
export async function removeInstallation(installationId) {
  const client = getClient();
  if (!client) return { success: false, error: 'Notification Hubs not configured' };

  try {
    await client.deleteInstallation(installationId);
    return { success: true };
  } catch (err) {
    console.error('[notificationHubs.removeInstallation]', err.message);
    return { success: false, error: err.message };
  }
}

/**
 * Send a push notification to a single user identified by the tag `user:<userId>`.
 *
 * @param {string} userId        - MongoDB user _id (string)
 * @param {object} notification  - { title, body, data? }
 */
export async function sendToUser(userId, { title, body, data = {} }) {
  return _send(`user:${userId}`, { title, body, data });
}

/**
 * Send a push notification to a tag expression.
 * Examples:
 *   sendToSegment('role:employer')
 *   sendToSegment('role:freelancer && niche:Gastronomia')
 *
 * @param {string} tagExpression - ANH tag expression string
 * @param {object} notification  - { title, body, data? }
 */
export async function sendToSegment(tagExpression, { title, body, data = {} }) {
  return _send(tagExpression, { title, body, data });
}

// ---------------------------------------------------------------------------
// Internal helper
// ---------------------------------------------------------------------------

async function _send(tagExpression, { title, body, data = {} }) {
  const client = getClient();
  if (!client) return { success: false, error: 'Notification Hubs not configured' };

  const apnsPayload = {
    aps: { alert: { title, body }, sound: 'default' },
    ...data,
  };

  const fcmPayload = {
    message: {
      notification: { title, body },
      data: Object.fromEntries(Object.entries(data).map(([k, v]) => [k, typeof v === 'object' ? JSON.stringify(v) : String(v)])),
    },
  };

  const sendOptions = { tagExpression };

  try {
    const [apnsResult, fcmResult] = await Promise.allSettled([
      client.sendNotification(createAppleNotification({ body: JSON.stringify(apnsPayload) }), sendOptions),
      client.sendNotification(createFcmV1Notification({ body: JSON.stringify(fcmPayload) }), sendOptions),
    ]);

    return {
      success: true,
      apns: apnsResult.status === 'fulfilled' ? apnsResult.value : { error: apnsResult.reason?.message },
      fcm: fcmResult.status === 'fulfilled' ? fcmResult.value : { error: fcmResult.reason?.message },
    };
  } catch (err) {
    console.error('[notificationHubs._send]', err.message);
    return { success: false, error: err.message };
  }
}
